version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:1.25.4-alpine
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
